# Generated by Django 3.2.9 on 2021-12-06 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_Name', models.CharField(choices=[('ACE', 'ACE'), ('PBA', 'PBA'), ('TDA', 'TDA'), ('Marketplace', 'Marketplace'), ('IAP', 'IAP'), ('Service Catalogue', 'Service Catalogue')], default='ACE', max_length=20)),
                ('NotiTrigger', models.CharField(choices=[('SSL certificate Expiry', 'SSL certificate Expiry'), ('Password expiry', 'Password expiry'), ('Client_secrets', 'Client_secrets'), ('License_expiry', 'License_expiry'), ('Access to roles expiry', 'Access to roles expiry')], default='SSL certificate Expiry', max_length=40)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry', models.DateTimeField()),
                ('frequency', models.CharField(choices=[('hrs', 'hrs'), ('days', 'days'), ('months', 'months'), ('years', 'years')], default='hrs', max_length=10)),
                ('nos', models.CharField(max_length=2)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
